### ISSUE TITLE
ES6 support would be great

### ISSUE THREAD

**Issue by tchakabam** [gunar/callgraph#12]
Great idea for a tool, really missing that right now.

Why not use Babel? (I read the comment, but can't imagine that this parser misses what is needed to create a call-graph, but I may be wrong ...)

**Comment by gunar** [comment]
Thanks!

Callgraph already has ES6 support. [It uses Babel programatically](https://github.com/gunar/callgraph/blob/master/parser.js#L33) to convert source code before analysing it. It's the easiest way I found so far.

Otherwise, always open to try out new parser.
